/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.MTDS_Main;

/**
 *
 * @author DanielSQ
 */
public class FRM_Line extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
    private final MTDS_Main mainMTDS;
    
    private String tipo;
    
    /**
     * Creates new form FRM_Linea
     * @param mainMTDS
     * @param tipo
     */
    public FRM_Line(MTDS_Main mainMTDS, String tipo) {
        initComponents();
        this.mainMTDS = mainMTDS;
        this.tipo = tipo;
        setTitle();
        this.setLocation(850,175);
    }
    
    /**
     * set title depending on tipo
     */
    public final void setTitle()
    {
        if(tipo.equals("ServCli"))
        {
            this.setTitle("Administrar Servicio al Cliente");
        }
        else if(tipo.equals("Cajas"))
        {
            this.setTitle("Administrar Cajas");
        }
    }

    /**
     * @return the Serv
     */
    public String getTipo() {
        return tipo;
    }

    /**
     * @param tipo
     */
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Fila = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_Fila = new javax.swing.JTextArea();
        lbl_Atendiendo = new javax.swing.JLabel();
        lbl_Nombre = new javax.swing.JLabel();
        tf_Nombre = new javax.swing.JTextField();
        lbl_Edad = new javax.swing.JLabel();
        tf_Edad = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btn_Refresh = new javax.swing.JButton();

        lbl_Fila.setFont(new java.awt.Font("Myriad Pro", 1, 18)); // NOI18N
        lbl_Fila.setText("Fila");

        ta_Fila.setColumns(20);
        ta_Fila.setRows(5);
        jScrollPane1.setViewportView(ta_Fila);

        lbl_Atendiendo.setFont(new java.awt.Font("Myriad Pro", 1, 18)); // NOI18N
        lbl_Atendiendo.setText("Atendiendo");

        lbl_Nombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_Nombre.setText("Nombre");

        tf_Nombre.setEditable(false);

        lbl_Edad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_Edad.setText("Edad");

        tf_Edad.setEditable(false);

        jButton1.setFont(new java.awt.Font("Myriad Pro", 1, 18)); // NOI18N
        jButton1.setText("Avanzar");

        btn_Refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/refresh.png"))); // NOI18N
        btn_Refresh.setMaximumSize(new java.awt.Dimension(48, 48));
        btn_Refresh.setMinimumSize(new java.awt.Dimension(48, 48));
        btn_Refresh.setPreferredSize(new java.awt.Dimension(48, 48));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Fila))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Atendiendo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbl_Nombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_Edad, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Refresh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_Nombre)
                            .addComponent(tf_Edad, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Fila)
                    .addComponent(lbl_Atendiendo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Nombre)
                            .addComponent(tf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Edad)
                            .addComponent(tf_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Refresh;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Atendiendo;
    private javax.swing.JLabel lbl_Edad;
    private javax.swing.JLabel lbl_Fila;
    private javax.swing.JLabel lbl_Nombre;
    private javax.swing.JTextArea ta_Fila;
    private javax.swing.JTextField tf_Edad;
    private javax.swing.JTextField tf_Nombre;
    // End of variables declaration//GEN-END:variables
}
