/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.CNTRL_Add;
import Model.MTDS_Main;
import javax.swing.ButtonGroup;

/**
 *
 * @author DanielSQ
 */
public class FRM_Add extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
    
    private MTDS_Main mainMTDS;
    private final CNTRL_Add controller;
    
    private ButtonGroup buttonGroup;
    
    private boolean prioridad;
    
    /**
     * Creates new form Add
     * @param mainMTDS
     */
    public FRM_Add(MTDS_Main mainMTDS) {
        this.setLocation(300,175);
        initComponents();
        this.mainMTDS = mainMTDS;
        controller = new CNTRL_Add(this);
        addActionListener();
        groupRadioButtons();
    }
    
    /**
     * Group radio buttons
     */
    public final void groupRadioButtons()
    {
        buttonGroup = new ButtonGroup();
        
        buttonGroup.add(rbtn_Atencion);
        buttonGroup.add(rbtn_Cajas);
    }
    
    /**
     * add controller to button
     */
    public final void addActionListener()
    {
        btn_Agregar.addActionListener(controller);
    }

    /**
     * @return the mainMTDS
     */
    public MTDS_Main getMainMTDS() {
        return mainMTDS;
    }

    /**
     * @param mainMTDS the mainMTDS to set
     */
    public void setMainMTDS(MTDS_Main mainMTDS) {
        this.mainMTDS = mainMTDS;
    }

    /**
     * @return the prioridad
     */
    public boolean isPrioridad() {
        return prioridad;
    }

    /**
     * @param prioridad the prioridad to set
     */
    public void setPrioridad(boolean prioridad) {
        this.prioridad = prioridad;
    }
    
    /**
     * Returns whether Cajas is selected
     * @return cajas selected
     */
    public boolean isCajasSelected()
    {
        return rbtn_Cajas.isSelected();
    }
    
    /**
     * Returns wheter Atencion is selected
     * @return atencion selected
     */
    public boolean isAtencionSelected()
    {
        return rbtn_Atencion.isSelected();
    }
    
    /**
     * Returns whether Discapacidad is selected
     * @return discapacidad selected
     */
    public boolean isDiscapacidadSelected()
    {
        return btn_Agregar.isSelected();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        lbl_Nombre = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        lbl_Edad = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        lbl_Servicio = new javax.swing.JLabel();
        rbtn_Cajas = new javax.swing.JRadioButton();
        rbtn_Atencion = new javax.swing.JRadioButton();
        chb_Prioridad = new javax.swing.JCheckBox();
        btn_Agregar = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setTitle("Agregar a la Fila");

        lbl_Nombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_Nombre.setText("Nombre");

        lbl_Edad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_Edad.setText("Edad");

        lbl_Servicio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_Servicio.setText("Servicio");

        rbtn_Cajas.setText("Cajas");

        rbtn_Atencion.setText("Atención al Cliente");
        rbtn_Atencion.setToolTipText("");
        rbtn_Atencion.setActionCommand("AtencionCliente");

        chb_Prioridad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chb_Prioridad.setText("Discapacidad");
        chb_Prioridad.setActionCommand("Prioridad");

        btn_Agregar.setFont(new java.awt.Font("Myriad Pro", 1, 18)); // NOI18N
        btn_Agregar.setText("Add");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Nombre)
                            .addComponent(lbl_Edad))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_Servicio)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtn_Atencion)
                            .addComponent(rbtn_Cajas)
                            .addComponent(chb_Prioridad)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Nombre)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Edad)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Servicio)
                    .addComponent(rbtn_Cajas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtn_Atencion)
                .addGap(18, 18, 18)
                .addComponent(chb_Prioridad)
                .addGap(18, 18, 18)
                .addComponent(btn_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Agregar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox chb_Prioridad;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lbl_Edad;
    private javax.swing.JLabel lbl_Nombre;
    private javax.swing.JLabel lbl_Servicio;
    private javax.swing.JRadioButton rbtn_Atencion;
    private javax.swing.JRadioButton rbtn_Cajas;
    // End of variables declaration//GEN-END:variables
}
